Document: namecoin-core
Title: Debian namecoin-core Manual
Author: <insert document author here>
Abstract: This manual describes what namecoin-core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/namecoin-core/namecoin-core.sgml.gz

Format: postscript
Files: /usr/share/doc/namecoin-core/namecoin-core.ps.gz

Format: text
Files: /usr/share/doc/namecoin-core/namecoin-core.text.gz

Format: HTML
Index: /usr/share/doc/namecoin-core/html/index.html
Files: /usr/share/doc/namecoin-core/html/*.html
